/*
 * main_events.c
 *
 *  Created on: Feb 20, 2021
 *      Author: zegeye
 */
#include "main.h"
#include "config.h"
#include "cli.h"
#include "i2c.h"
#include "uart.h"
#include "adc.h"
#include "tmp1075.h"
#include "rtd.h"
#include "thermalcontrol.h"

void main_events()
{
    // service other events generated by non-timer ISRs
    while(gstMainEvts.wAll)
    {
        // service tick (blink:toggle p1.0) and expired timers
        if(gstMainEvts.bits.svcTicker)
        {
            serviceTimers();
        }

        if(gstMainEvts.bits.svcUartRx == true)
        {
            UART_svcUartRx();
        }

        if(gstMainEvts.bits.svcUartTx == true)
        {
            UART_svcUartTx();
        }

        if(gstMainEvts.bits.svcTestUartTx == true)
        {
            UART_testTransmit();
        }

        if(gstMainEvts.bits.svcDiag == true)
        {
            maintainDiagMsgDisplay();
        }

        if(gstMainEvts.bits.svcI2c == true)
        {
            if (stI2cMessageActive.eI2cSnsrType == I2C_TEMP_SNSR_TMP1075)
            {
                processTmp1075I2cMsg();
            }
        }

        if(gstMainEvts.bits.xformI2cMsg == true)
        {
            xformTmp1075Adc2Temp();
        }

        if(gstMainEvts.bits.svcRtdAdc == true)
        {
            transformRtdAdcToTmp();
        }

        if(gstMainEvts.bits.svcHtrTmr == true)
        {
            disableHtrTmr();
        }
    }


}



